class AddMerchantUserPermissionColumns < ActiveRecord::Migration[7.0]
  def up
    add_column :merchant_users, :allow_read_merchant_user, :integer, default: 0
    add_column :merchant_users, :allow_create_merchant_user, :integer, default: 0
    add_column :merchant_users, :allow_update_merchant_user, :integer, default: 0
    add_column :merchant_users, :allow_delete_merchant_user, :integer, default: 0
    add_column :merchant_users, :allow_read_reserve_frame, :integer, default: 0
    add_column :merchant_users, :allow_create_reserve_frame, :integer, default: 0
    add_column :merchant_users, :allow_update_reserve_frame, :integer, default: 0
    add_column :merchant_users, :allow_delete_reserve_frame, :integer, default: 0
    add_column :merchant_users, :allow_read_reservation, :integer, default: 0
    add_column :merchant_users, :allow_create_reservation, :integer, default: 0
    add_column :merchant_users, :allow_confirm_reservation, :integer, default: 0
    add_column :merchant_users, :allow_cancel_reservation, :integer, default: 0
    add_column :merchant_users, :allow_read_ticket_master, :integer, default: 0
    add_column :merchant_users, :allow_create_ticket_master, :integer, default: 0
    add_column :merchant_users, :allow_update_ticket_master, :integer, default: 0
    add_column :merchant_users, :allow_delete_ticket_master, :integer, default: 0
    add_column :merchant_users, :allow_read_monthly_payment_plan, :integer, default: 0
    add_column :merchant_users, :allow_create_monthly_payment_plan, :integer, default: 0
    add_column :merchant_users, :allow_update_monthly_payment_plan, :integer, default: 0
    add_column :merchant_users, :allow_delete_monthly_payment_plan, :integer, default: 0
    add_column :merchant_users, :allow_read_resource, :integer, default: 0
    add_column :merchant_users, :allow_create_resource, :integer, default: 0
    add_column :merchant_users, :allow_update_resource, :integer, default: 0
    add_column :merchant_users, :allow_delete_resource, :integer, default: 0
    add_column :merchant_users, :allow_read_product, :integer, default: 0
    add_column :merchant_users, :allow_create_product, :integer, default: 0
    add_column :merchant_users, :allow_update_product, :integer, default: 0
    add_column :merchant_users, :allow_delete_product, :integer, default: 0
    add_column :merchant_users, :allow_update_delivery_setting, :integer, default: 0
    add_column :merchant_users, :allow_update_product_shipping_status, :integer, default: 0
    add_column :merchant_users, :allow_read_customer, :integer, default: 0
    add_column :merchant_users, :allow_create_customer, :integer, default: 0
    add_column :merchant_users, :allow_update_customer, :integer, default: 0
    add_column :merchant_users, :allow_delete_customer, :integer, default: 0
    add_column :merchant_users, :allow_read_customer_group, :integer, default: 0
    add_column :merchant_users, :allow_create_customer_group, :integer, default: 0
    add_column :merchant_users, :allow_update_customer_group, :integer, default: 0
    add_column :merchant_users, :allow_delete_customer_group, :integer, default: 0
    add_column :merchant_users, :allow_read_webpage, :integer, default: 0
    add_column :merchant_users, :allow_create_webpage, :integer, default: 0
    add_column :merchant_users, :allow_update_webpage, :integer, default: 0
    add_column :merchant_users, :allow_delete_webpage, :integer, default: 0
    add_column :merchant_users, :allow_read_questionnaire_master, :integer, default: 0
    add_column :merchant_users, :allow_create_questionnaire_master, :integer, default: 0
    add_column :merchant_users, :allow_update_questionnaire_master, :integer, default: 0
    add_column :merchant_users, :allow_delete_questionnaire_master, :integer, default: 0
    add_column :merchant_users, :allow_read_questionnaire_answer, :integer, default: 0
    add_column :merchant_users, :allow_read_sales, :integer, default: 0
    add_column :merchant_users, :allow_read_payment_request, :integer, default: 0
    add_column :merchant_users, :allow_create_payment_request, :integer, default: 0
    add_column :merchant_users, :allow_read_credit_card, :integer, default: 0
    add_column :merchant_users, :allow_update_credit_card, :integer, default: 0
    add_column :merchant_users, :allow_read_stripe_business_info, :integer, default: 0
    add_column :merchant_users, :allow_update_stripe_business_info, :integer, default: 0
  end

  def down
    remove_column :merchant_users, :allow_read_merchant_user, :integer, default: 0
    remove_column :merchant_users, :allow_create_merchant_user, :integer, default: 0
    remove_column :merchant_users, :allow_update_merchant_user, :integer, default: 0
    remove_column :merchant_users, :allow_delete_merchant_user, :integer, default: 0
    remove_column :merchant_users, :allow_read_reserve_frame, :integer, default: 0
    remove_column :merchant_users, :allow_create_reserve_frame, :integer, default: 0
    remove_column :merchant_users, :allow_update_reserve_frame, :integer, default: 0
    remove_column :merchant_users, :allow_delete_reserve_frame, :integer, default: 0
    remove_column :merchant_users, :allow_read_reservation, :integer, default: 0
    remove_column :merchant_users, :allow_create_reservation, :integer, default: 0
    remove_column :merchant_users, :allow_confirm_reservation, :integer, default: 0
    remove_column :merchant_users, :allow_cancel_reservation, :integer, default: 0
    remove_column :merchant_users, :allow_read_ticket_master, :integer, default: 0
    remove_column :merchant_users, :allow_create_ticket_master, :integer, default: 0
    remove_column :merchant_users, :allow_update_ticket_master, :integer, default: 0
    remove_column :merchant_users, :allow_delete_ticket_master, :integer, default: 0
    remove_column :merchant_users, :allow_read_monthly_payment_plan, :integer, default: 0
    remove_column :merchant_users, :allow_create_monthly_payment_plan, :integer, default: 0
    remove_column :merchant_users, :allow_update_monthly_payment_plan, :integer, default: 0
    remove_column :merchant_users, :allow_delete_monthly_payment_plan, :integer, default: 0
    remove_column :merchant_users, :allow_read_resource, :integer, default: 0
    remove_column :merchant_users, :allow_create_resource, :integer, default: 0
    remove_column :merchant_users, :allow_update_resource, :integer, default: 0
    remove_column :merchant_users, :allow_delete_resource, :integer, default: 0
    remove_column :merchant_users, :allow_read_product, :integer, default: 0
    remove_column :merchant_users, :allow_create_product, :integer, default: 0
    remove_column :merchant_users, :allow_update_product, :integer, default: 0
    remove_column :merchant_users, :allow_delete_product, :integer, default: 0
    remove_column :merchant_users, :allow_update_delivery_setting, :integer, default: 0
    remove_column :merchant_users, :allow_update_product_shipping_status, :integer, default: 0
    remove_column :merchant_users, :allow_read_customer, :integer, default: 0
    remove_column :merchant_users, :allow_create_customer, :integer, default: 0
    remove_column :merchant_users, :allow_update_customer, :integer, default: 0
    remove_column :merchant_users, :allow_delete_customer, :integer, default: 0
    remove_column :merchant_users, :allow_read_customer_group, :integer, default: 0
    remove_column :merchant_users, :allow_create_customer_group, :integer, default: 0
    remove_column :merchant_users, :allow_update_customer_group, :integer, default: 0
    remove_column :merchant_users, :allow_delete_customer_group, :integer, default: 0
    remove_column :merchant_users, :allow_read_webpage, :integer, default: 0
    remove_column :merchant_users, :allow_create_webpage, :integer, default: 0
    remove_column :merchant_users, :allow_update_webpage, :integer, default: 0
    remove_column :merchant_users, :allow_delete_webpage, :integer, default: 0
    remove_column :merchant_users, :allow_read_questionnaire_master, :integer, default: 0
    remove_column :merchant_users, :allow_create_questionnaire_master, :integer, default: 0
    remove_column :merchant_users, :allow_update_questionnaire_master, :integer, default: 0
    remove_column :merchant_users, :allow_delete_questionnaire_master, :integer, default: 0
    remove_column :merchant_users, :allow_read_questionnaire_answer, :integer, default: 0
    remove_column :merchant_users, :allow_read_sales, :integer, default: 0
    remove_column :merchant_users, :allow_read_payment_request, :integer, default: 0
    remove_column :merchant_users, :allow_create_payment_request, :integer, default: 0
    remove_column :merchant_users, :allow_read_credit_card, :integer, default: 0
    remove_column :merchant_users, :allow_update_credit_card, :integer, default: 0
    remove_column :merchant_users, :allow_read_stripe_business_info, :integer, default: 0
    remove_column :merchant_users, :allow_update_stripe_business_info, :integer, default: 0
  end
end
