default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME") %>

production:
  <<: *default
  pool: 32
  database: <%= ENV.fetch("DATABASE_NAME") %>
