version: '3'

services:
  smartlesson_frontend:
    container_name: smartlesson_frontend
    build:
      context: frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend:/app/frontend
    tty: true
    ports:
      - 3111:3000
    networks:
      - smartlesson_network

networks:
  smartlesson_network:
