export interface ResourceParam {
  id: number
  name: string
  quentity: number
  reception_time_setting: string
  mon_start?: string
  mon_end?: string
  tue_start?: string
  tue_end?: string
  wed_start?: string
  wed_end?: string
  thu_start?: string
  thu_end?: string
  fri_start?: string
  fri_end?: string
  sat_start?: string
  sat_end?: string
  sun_start?: string
  sun_end?: string
  holiday_start?: string
  holiday_end?: string
  mon_break_start?: string
  mon_break_end?: string
  tue_break_start?: string
  tue_break_end?: string
  wed_break_start?: string
  wed_break_end?: string
  thu_break_start?: string
  thu_break_end?: string
  fri_break_start?: string
  fri_break_end?: string
  sat_break_start?: string
  sat_break_end?: string
  sun_break_start?: string
  sun_break_end?: string
  holiday_break_start?: string
  holiday_break_end?: string
}
