version: '3'

services:
  square_eight_rails_api_demo:
    container_name: square_eight_rails_api_demo
    build:
      context: ../rails_api
      dockerfile: docker/app/Dockerfile
    env_file: ../rails_api/docker/docker_ec2_demo.env
    command: bash -c "/workdir/docker/app/entrypoint_api_demo.sh"
    volumes:
      - ../rails_api:/workdir
    tty: true
    stdin_open: true
    ports:
      - 80:3000
    networks:
      - square_eight_network
  square_eight_redis_demo:
    container_name: square_eight_redis_demo
    build:
      context: ../rails_api
      dockerfile: docker/redis/Dockerfile
    volumes:
      - ../rails_api/cache/redis/data:/data
    ports:
      - "16379:6379"
    networks:
      - square_eight_network

networks:
  square_eight_network:
